Unit test
Star-Academy/Summer1401-SE-Team05 pull request #3
Opened 2022-08-01 07:28 UTC by hosseinmasoodi

2022-08-01 07:49 UTC, ali-bonaftizadeh reviewed
Nice job!

2022-08-01 07:49 UTC, ali-bonaftizadeh commented on phase4/.vscode/settings.json
> +}
This file is unnecessary and you'd better add It to gitignore.

2022-08-01 07:49 UTC, ali-bonaftizadeh commented on phase4/SimpleCalculator.BusinessTest/OperatorBusiness/OperatorProviderTests.cs
> +}
Having commented code violates clean code rules.

2022-08-01 12:37 UTC, ali-bonaftizadeh approved these changes

2022-08-02 08:26 UTC, amirarab888 requested changes
نام گذاری توابع تست استاندارد نیست
فایل های اضافی ایگنور نشده اند
تاپ ماژول ها تست شده اند؟ چرا غیر از یک تست, در جایی, چیزی ماک نشده است؟

2022-08-03 18:32 UTC, RAAvenger reviewed
سلام
خسته نباشید
چندتا نکته جزئی هست که چندین بار تکرار شدن
اصلاحشون کنید

2022-08-03 18:32 UTC, RAAvenger commented on phase4/SimpleCalculator.BusinessTest/OperatorBusiness/OperatorProviderTests.cs
> +        OperatorProvider operatorProvider = new OperatorProvider();
var

2022-08-03 18:32 UTC, RAAvenger commented on phase4/SimpleCalculator.BusinessTest/OperatorBusiness/Operators/DivisionOperatorTests.cs
> +    [InlineData(int.MaxValue, 1, int.MaxValue)]
اگر حالت مرزی نیستن یکیشونم کافیه

2022-08-03 18:32 UTC, RAAvenger commented on phase4/SimpleCalculator.BusinessTest/OperatorBusiness/Operators/DivisionOperatorTests.cs
> +        Assert.Equal(ex.Message, "Attempted to divide by zero.");
اینجا Act و Assert با هم انجام میشن

2022-08-03 18:32 UTC, RAAvenger commented on phase4/SimpleCalculator.BusinessTest/SimpleCalculatorTests.cs
> +        _operatorProvider.GetOperator(Arg.Is(operatorType)).Returns(mockedOperator);
ترتیب اینا عجیبه
منطقا اول ماک‌ها انجام میشن و در نهایت sut ایجاد میشه

2022-08-09 06:32 UTC, mojo-izadi commented
> نام گذاری توابع تست استاندارد نیست فایل های اضافی ایگنور نشده اند تاپ ماژول ها تست شده اند؟ چرا غیر از یک تست, در جایی, چیزی ماک نشده است؟

نام گزاری اصلاح شد

تمام کلاس‌های غیر abstract تست شده‌اند
تنها یکی از کلاس‌ها برای تست نیاز به ماک کردن داشت و بقیه کلاس‌هات در حدی مستقل بودند که نیاز به ماک کردن نبود

2022-08-12 17:45 UTC, RAAvenger approved these changes
سلام
خسته نباشید

2022-08-13 07:55 UTC, amirarab888 approved these changes

2022-08-13 08:11 UTC, merged