EFcore
Star-Academy/Summer1401-SE-Team05 pull request #6
Opened 2022-08-14 06:05 UTC by mojo-izadi

2022-08-15 14:02 UTC, RAAvenger requested changes
سلام
خسته نباشید
سالید یادتون نره

2022-08-15 14:02 UTC, RAAvenger commented on phase8/DatabaseInitializer.cs
> +            "C:\\Users\\gamer\\OneDrive\\Desktop\\TopStudents\\scores.json"));
مسیر مطلق ندید
مسیر نسبی بدید
برای ایجاد مسیر هم از امکانات زبان استفاده کنید

2022-08-15 14:02 UTC, RAAvenger commented on phase8/Grade.cs
> +    public string Lesson { get; set; }
اگر یه دانش اموز یه درس رو توی دوتا ترم برداره این کاری که انجام دادید غلط میشه.

2022-08-15 14:02 UTC, RAAvenger commented on phase8/DatabaseInitializer.cs
> +            }
extract method

2022-08-15 14:02 UTC, RAAvenger commented on phase8/DatabaseInitializer.cs
> +            "C:\\Users\\gamer\\OneDrive\\Desktop\\TopStudents\\students.json"));
extract method

2022-08-15 14:02 UTC, RAAvenger commented on phase8/DatabaseInitializer.cs
> +        }
extract method

2022-08-16 07:03 UTC, mojo-izadi commented on phase8/Grade.cs
> +    public string Lesson { get; set; }
اگر ممکنه جایگزین ارائه بدید چون ما کلا از هر نمره فقط شماره دانشجویی، اسم درس و نمره رو داریم.
از طرفی هم اگر برای یه آبجکت pk تعریف نکنیم کد اکسپشن میده و مجبورمون می‌کنه تعریف کنیم.
اگر هم نمره رو به key اضافه کنیم نه کار تمیزی هست و نه مشکل رو حل می‌کنه.
مطمئنید لازمه این حالت رو در نظر بگیریم؟

2022-08-16 10:25 UTC, M79Montazer reviewed
.json files should not be included in PR's

2022-08-17 07:50 UTC, amirarab888 approved these changes
چند تا کامنت ریز گذاشتم, نکته دیگری ندارد.

2022-08-17 07:50 UTC, amirarab888 commented on phase8/DatabaseInitializer.cs
> +            context.SaveChanges();
مگه تغییری تو دیتا میخوای بدی که سیو کردید؟

2022-08-17 07:50 UTC, amirarab888 commented on phase8/Grade.cs
> +    public string Lesson { get; set; }
اگه یه دانشجو یه درس رو دو بار برداره چی؟ این جوری کلید تکراری میشه اکسپشن میخوری

2022-08-17 07:50 UTC, amirarab888 commented on phase8/PeopleContext.cs
> +    protected override void OnModelCreating(ModelBuilder modelBuilder)
کلا هر چیزی رو بتونید این جا به طور شفاف مشخص کنید بهتره, به دیفالت های asp تکیه کنید احتمال باگ میره بالا

2022-08-18 14:05 UTC, RAAvenger approved these changes
سلام
خسته نباشید

2022-08-18 15:48 UTC, merged